/**
 * Lightweight project data module — reads from the pre-built
 * data/projects-manifest.json instead of scanning the filesystem at runtime.
 *
 * This prevents Turbopack / NFT from tracing public/assets/03.Project into
 * every serverless function bundle, keeping each function well under 250 MB.
 *
 * The manifest is generated by scripts/generate-projects-manifest.mjs and
 * must be run before next build (see "prebuild" in package.json).
 */

import type { MediaAsset, MediaOrientation, Project, ProjectGalleryItem } from "./site-assets";
import rawManifest from "../data/projects-manifest.json";

// Re-export types so callers can import them from either module
export type { MediaAsset, MediaOrientation, Project, ProjectGalleryItem };

// Cast the raw JSON to the correct types
const manifest = rawManifest as Project[];

export async function getProjects(): Promise<Project[]> {
  return manifest;
}

export async function getProjectGalleries(): Promise<ProjectGalleryItem[]> {
  return manifest.map((p) => ({
    slug: p.slug,
    title: p.title,
    assets: p.assets,
  }));
}

export function getProjectBySlug(slug: string): Project | null {
  return manifest.find((p) => p.slug === slug) ?? null;
}
