/**
 * Lightweight project data module — reads from the pre-built
 * data/projects-manifest.json instead of scanning the filesystem at runtime.
 *
 * This prevents Turbopack / NFT from tracing public/assets/03.Project into
 * every serverless function bundle, keeping each function well under 250 MB.
 *
 * The manifest is generated by scripts/generate-projects-manifest.mjs and
 * must be run before next build (see "prebuild" in package.json).
 */

import type { MediaAsset, MediaOrientation, Project, ProjectGalleryItem } from "./site-assets";
import rawManifest from "../data/projects-manifest.json";

// Re-export types so callers can import them from either module
export type { MediaAsset, MediaOrientation, Project, ProjectGalleryItem };

interface Manifest {
  projects: Project[];
  collageImages: string[];
  projectMenuImage: string | null;
}

const manifest = rawManifest as Manifest;

export async function getProjects(): Promise<Project[]> {
  return manifest.projects;
}

export async function getProjectGalleries(): Promise<ProjectGalleryItem[]> {
  return manifest.projects.map((p) => ({
    slug: p.slug,
    title: p.title,
    assets: p.assets,
  }));
}

export function getProjectBySlug(slug: string): Project | null {
  return manifest.projects.find((p) => p.slug === slug) ?? null;
}

/** All project images for the home page collage — served from the CDN, no fs access. */
export async function getHomeProjectCollageImages(limit = 24): Promise<string[]> {
  return manifest.collageImages.slice(0, Math.max(1, limit));
}

/** Path to "Immagine menu home" inside public/assets/03.Project — pre-built in manifest. */
export async function getProjectMenuImage(): Promise<string | null> {
  return manifest.projectMenuImage ?? null;
}
